apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: reduced-azure-rke2-example
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: RKE2ControlPlaneTemplate
      name: rke2-control-plane
    machineInfrastructure:
      ref:
        kind: AzureMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: rke2-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureClusterTemplate
      name: azure-cluster
  workers:
    machineDeployments:
      - class: rke2-default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: RKE2ConfigTemplate
              name: rke2-default-worker-bootstrap
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AzureMachineTemplate
              name: rke2-default-worker
  variables:
    - name: subscriptionID
      metadata:
        annotations:
          turtles-capi.cattle.io/section: 'general'
          turtles-capi.cattle.io/group: 'Azure'
      required: true
      schema:
        openAPIV3Schema:
          description: "The Azure Subscription ID where the Cluster will be created."
          type: string
    # - name: location
    #   required: true
    #   annotations:
    #       turtles-capi.cattle.io/section: 'general'
    #       turtles-capi.cattle.io/group: 'Azure'
    #   schema:
    #     openAPIV3Schema:
    #       description: "The Azure location where the Cluster will be created."
    #       type: string
    #       enum:
    #         - australiaeast
    #         - francecentral
    #         - germanywestcentral
    #         - northcentralus
    #         - northeurope
    #         - switzerlandnorth
    #         - uksouth
    #         - westeurope
    #         - westus2
    # - name: resourceGroup
    #   metadata:
    #     annotations:
    #       turtles-capi.cattle.io/section: 'general'
    #       turtles-capi.cattle.io/group: 'Azure'
    #   required: true
    #   schema:
    #     openAPIV3Schema:
    #       description: "The Azure Resource Group where the Cluster will be created."
    #       type: string
    # - name: azureClusterIdentityName
    #   required: true
    #   schema:
    #     openAPIV3Schema:
    #       description: "The AzureClusterIdentity resource name referencing the credentials to create the Cluster."
    #       type: string
    #       default: "cluster-identity"
    - name: azureClusterIdentity
      metadata:
        annotations:
          turtles-capi.cattle.io/section: 'general'
          turtles-capi.cattle.io/group: 'Azure'
          turtles-capi.cattle.io/type: 'infrastructure.cluster.x-k8s.io.azureclusteridentity'
      required: true
      schema:
        openAPIV3Schema:
          description: 'The AzureClusterIdentity is a CRD that references a secret containing credentials used to authenticate with Azure. It should be in the same namespace or have allowedNamespaces specified.'
          type: object
          properties:
            name: 
              type: string
              default: cluster-identity
            namespace:
              type: string
              default: default
    # - name: imageGallery
    #   metadata:
    #     annotations:
    #       turtles-capi.cattle.io/section: 'workers'
    #   required: true
    #   schema:
    #     openAPIV3Schema:
    #       description: "The image Public gallery name."
    #       type: string
    #       default: "ClusterAPI-f72ceb4f-5159-4c26-a0fe-2ea738f0d019"
    # - name: imageName
    #   metadata:
    #     annotations:
    #       turtles-capi.cattle.io/section: 'workers'
    #       turtles-capi.cattle.io/highlight: 'warning'
    #   required: true
    #   schema:
    #     openAPIV3Schema:
    #       description: "This cluster's kubernetes version will be used to determined the version of this image to use. For example, if you want to create a v1.31.1+rke1r1 cluster, this image in this image gallery must contain a version named 1.31.1"
    #       type: string
    #       default: "capi-ubun2-2404"          
    - name: vmSize
      metadata:
        annotations:
          turtles-capi.cattle.io/section: 'workers'
      required: true
      schema:
        openAPIV3Schema:
          description: "The VM size used by machines."
          type: string
          default: "Standard_D2s_v3"
          enum:
          - Standard_D2s_v3
          - Standard_D12_v2
          - Standard_A2_v2
    # - name: registrationMethod
    #   metadata:
    #     annotations:
    #       turtles-capi.cattle.io/section: 'controlplane'
    #   required: true
    #   schema:
    #     openAPIV3Schema:
    #       description: "Registration method to use. Defaults to control-plane endpoint (empty string). Immutable once is set."
    #       type: string
    #       default: ""
    #       enum:
    #         - internal-first
    #         - internal-only-ips
    #         - external-only-ips
    #         - address
    #         - control-plane-endpoint
    #         - ""
  patches:
    - name: azureClusterTemplate
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: "/spec/template/spec/subscriptionID"
              valueFrom:
                variable: subscriptionID
            # - op: add
            #   path: "/spec/template/spec/location"
            #   valueFrom:
            #     variable: location
            # - op: add
            #   path: "/spec/template/spec/resourceGroup"
            #   valueFrom:
            #     variable: resourceGroup
            - op: add
              path: "/spec/template/spec/resourceGroup"
              valueFrom:
                template: '{{ .builtin.cluster.name }}-group'
            # - op: add
            #   path: "/spec/template/spec/identityRef/name"
            #   valueFrom:
            #     variable: azureClusterIdentityName
            - op: add
              path: "/spec/template/spec/identityRef/name"
              valueFrom:
                template: '{{ .azureClusterIdentity.name }}'
            - op: add
              path: "/spec/template/spec/networkSpec/vnet/name"
              valueFrom:
                variable: builtin.cluster.name
    - name: azureMachineTemplate
      definitions:
        - selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: RKE2ControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/files/-
              valueFrom:
                template: |
                    contentFrom:
                      secret:
                        key: control-plane-azure.json
                        name: "{{ .builtin.controlPlane.machineTemplate.infrastructureRef.name }}-azure-json"
                    owner: root:root
                    path: /etc/kubernetes/azure.json
                    permissions: "0644"
            # - op: add
            #   path: /spec/template/spec/registrationMethod
            #   valueFrom:
            #     variable: registrationMethod
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureMachineTemplate
            matchResources:
              controlPlane: true
              machineDeploymentClass:
                names:
                  - rke2-default-worker
          jsonPatches:
            - op: add
              path: "/spec/template/spec/image/computeGallery/gallery"
              valueFrom:
                variable: imageGallery
            - op: add
              path: "/spec/template/spec/image/computeGallery/name"
              valueFrom:
                variable: imageName
            - op: replace
              path: /spec/template/spec/image/computeGallery/version
              valueFrom:
                template: '{{ trimPrefix "v" (trimSuffix "+rke2r1" .builtin.cluster.topology.version) }}'
            - op: add
              path: "/spec/template/spec/vmSize"
              valueFrom:
                variable: vmSize
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: reduced-rke2-default-worker-bootstrap
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterTemplate
metadata:
  name: reduced-azure-cluster
spec:
  template:
    spec:
      location: westus2
      identityRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterIdentity
        name: cluster-identity
      networkSpec:
        subnets:
        - name: control-plane-subnet
          role: control-plane
        - name: node-subnet
          natGateway:
            name: node-natgateway
          role: node
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlaneTemplate
metadata:
  name: reduced-rke2-control-plane
spec:
  template:
    spec:
      registrationMethod: ""
      rolloutStrategy:
        type: "RollingUpdate"
        rollingUpdate:
          maxSurge: 1
      agentConfig: {}
      serverConfig:
        cni: none
        cloudProviderName: external
        disableComponents:
          kubernetesComponents:
          - cloudController
        kubeAPIServer:
          extraArgs:
          - --anonymous-auth=true
      files:
        - owner: root:root
          path: /etc/kubernetes/azure.json
          permissions: "0644"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: reduced-rke2-control-plane
spec:
  template:
    spec:
      image:
        computeGallery: 
          gallery: ClusterAPI-f72ceb4f-5159-4c26-a0fe-2ea738f0d019
          name: capi-ubun2-2404
          version: "TO_BE_REPLACED_BY_PATCH"
      osDisk:
        diskSizeGB: 128
        osType: Linux
      vmSize: "TO_BE_REPLACED_BY_PATCH"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: reduced-rke2-default-worker
spec:
  template:
    spec:
      image:
        computeGallery: 
          gallery: ClusterAPI-f72ceb4f-5159-4c26-a0fe-2ea738f0d019
          name: capi-ubun2-2404
          version: "TO_BE_REPLACED_BY_PATCH"
      osDisk:
        diskSizeGB: 30
        osType: Linux
      vmSize: "TO_BE_REPLACED_BY_PATCH"