apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: demo-poor-azure-rke2-example
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: RKE2ControlPlaneTemplate
      name: demo-poor-rke2-control-plane
    machineInfrastructure:
      ref:
        kind: AzureMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: demo-poor-rke2-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureClusterTemplate
      name: demo-poor-azure-cluster
  workers:
    machineDeployments:
      - class: rke2-default-worker
        namingStrategy:
          template: "{{ .cluster.name }}-{{ .machineDeployment.topologyName }}-{{ .random }}"
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: RKE2ConfigTemplate
              name: demo-poor-rke2-default-worker-bootstrap
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AzureMachineTemplate
              name: demo-poor-rke2-default-worker
  variables:
    - name: subscriptionID
      required: true
      metadata: 
        annotations:
          turtles-capi.cattle.io/section: 'general'
      schema:
        openAPIV3Schema:
          description: "The Azure Subscription ID where the Cluster will be created."
          type: string
    - name: azureClusterIdentityName
      required: true
      metadata: 
        annotations:
          turtles-capi.cattle.io/section: 'general'
      schema:
        openAPIV3Schema:
          description: "The AzureClusterIdentity resource name referencing the credentials to create the Cluster."
          type: string
          default: "cluster-identity"     
  patches:
    - name: azureClusterTemplate
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: "/spec/template/spec/subscriptionID"
              valueFrom:
                variable: subscriptionID
            - op: add
              path: "/spec/template/spec/resourceGroup"
              valueFrom:
                template: '{{ .builtin.cluster.name  }}-resource-group'
            - op: add
              path: "/spec/template/spec/identityRef/name"
              valueFrom:
                variable: azureClusterIdentityName
            - op: add
              path: "/spec/template/spec/networkSpec/vnet/name"
              valueFrom:
                variable: builtin.cluster.name
    - name: azureMachineTemplate
      definitions:
        - selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: RKE2ControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/files/-
              valueFrom:
                template: |
                    contentFrom:
                      secret:
                        key: control-plane-azure.json
                        name: "{{ .builtin.controlPlane.machineTemplate.infrastructureRef.name }}-azure-json"
                    owner: root:root
                    path: /etc/kubernetes/azure.json
                    permissions: "0644"
            - op: add
              path: /spec/template/spec/registrationMethod
              valueFrom:
                template: '{{ "" }}'
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureMachineTemplate
            matchResources:
              controlPlane: true
              machineDeploymentClass:
                names:
                  - rke2-default-worker
          jsonPatches:
            - op: replace
              path: /spec/template/spec/image/computeGallery/version
              valueFrom:
                template: '{{ trimPrefix "v" (trimSuffix "+rke2r1" .builtin.cluster.topology.version) }}'
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: demo-poor-rke2-default-worker-bootstrap
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterTemplate
metadata:
  name: demo-poor-azure-cluster
spec:
  template:
    spec:
      location: 'eastus2'
      identityRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterIdentity
        name: cluster-identity
      networkSpec:
        subnets:
        - name: control-plane-subnet
          role: control-plane
        - name: node-subnet
          natGateway:
            name: node-natgateway
          role: node
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlaneTemplate
metadata:
  name: demo-poor-rke2-control-plane
spec:
  template:
    spec:
      rolloutStrategy:
        type: "RollingUpdate"
        rollingUpdate:
          maxSurge: 1
      agentConfig: {}
      serverConfig:
        cni: none
        cloudProviderName: external
        disableComponents:
          kubernetesComponents:
          - cloudController
        kubeAPIServer:
          extraArgs:
          - --anonymous-auth=true
      files:
        - owner: root:root
          path: /etc/kubernetes/azure.json
          permissions: "0644"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: demo-poor-rke2-control-plane
spec:
  template:
    spec:
      vmSize: Standard_D2s_v3
      image:
        computeGallery: 
          gallery: "ClusterAPI-f72ceb4f-5159-4c26-a0fe-2ea738f0d019"
          name: "capi-ubun2-2404"
          version: "TO_BE_REPLACED_BY_PATCH"
      osDisk:
        diskSizeGB: 128
        osType: Linux
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: demo-poor-rke2-default-worker
spec:
  template:
    spec:
      vmSize: Standard_D2s_v3
      image:
        computeGallery: 
          gallery: "ClusterAPI-f72ceb4f-5159-4c26-a0fe-2ea738f0d019"
          name: "capi-ubun2-2404"
          version: "TO_BE_REPLACED_BY_PATCH"
      osDisk:
        diskSizeGB: 30
        osType: Linux
